name: Auto Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour at minute 0
  workflow_dispatch:     # manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v3
        with:
          ref: main  # change if your default branch is different

      - name: Add upstream remote
        run: git remote add upstream https://github.com/discord/discord-api-docs.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync upstream changes"

      - name: Push changes to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
